import Header from '@/components/Header'
import Navbar from '@/components/Navbar'
import './globals.css'
import Provider from './Provider'

export const metadata = {
  title: 'IMBd Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider >
          <Header></Header>
          <Navbar></Navbar>
          {children}
        </Provider>
      </body>
    </html>
  )
}
