import Header from '@/components/Header'
import './globals.css'

export const metadata = {
  title: 'IMBd Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header></Header>
        {children}
      </body>
    </html>
  )
}
